chore: 🤖 Extend environment variable support via CI/CD for ZenDesk's service (#131)
## Why?

Extend environment variable support via CI/CD for ZenDesk's service

## How?

- Add environment variables in CI/CD as env. variables and secrets where
it applies
- Created a script to automate the env variable update process on remote
service via CI/CD
- Update Systemd service template by including the EnvironmentFile=
directive which value corresponds to the environment variables file
created in the automation script
- Update docs

## Tickets?

-
[AS-303](https://linear.app/fleekxyz/issue/AS-303/extend-environment-variable-support-via-cicd-for-zendesks-service)

## Contribution checklist?

- [x] The commit messages are detailed
- [x] The `build` command runs locally
- [ ] Assets or static content are linked and stored in the project
- [ ] Document filename is named after the slug
- [ ] You've reviewed spelling using a grammar checker
- [ ] For documentation, guides or references, you've tested the
commands and steps
- [ ] You've done enough research before writing

## Security checklist?

- [x] Sensitive data has been identified and is being protected properly
- [ ] Injection has been prevented (parameterized queries, no eval or
system calls)
- [ ] The Components are escaping output (to prevent XSS)

## References?

Optionally, provide references such as links

## Preview?

<img width="891" alt="Screenshot 2024-08-12 at 13 11 49"
src="https://github.com/user-attachments/assets/b008da1b-70ef-4114-b3d7-2330c3a331a7">

<img width="1660" alt="Screenshot 2024-08-12 at 13 12 39"
src="https://github.com/user-attachments/assets/81d592b8-c909-4978-8b23-f03ac4970178">

diff --git a/.github/workflows/support-service-update.yml b/.github/workflows/support-service-update.yml
--- a/.github/workflows/support-service-update.yml
+++ b/.github/workflows/support-service-update.yml
@@ -21,6 +21,15 @@ jobs:
         SUPPORT_SERVICE_PATHNAME: ${{ secrets.SUPPORT_SERVICE_PATHNAME }}
         SUPPORT_SERVICE_SYSTEMD_NAME: ${{ secrets.SUPPORT_SERVICE_SYSTEMD_NAME }}
         GITHUB_REF_NAME: ${{ env.GITHUB_REF_NAME }}
+        PRIVATE_ZENDESK_EMAIL: ${{ secrets.PRIVATE_ZENDESK_EMAIL }}
+        PRIVATE_ZENDESK_API_KEY: ${{ secrets.PRIVATE_ZENDESK_API_KEY }}
+        PRIVATE_ZENDESK_HOSTNAME: ${{ secrets.PRIVATE_ZENDESK_HOSTNAME }}
+        PUBLIC_SUPPORT_API_HOST: ${{ env.PUBLIC_SUPPORT_API_HOST }}
+        SUPPORT_ALLOW_ORIGIN_ADDR: ${{ env.SUPPORT_ALLOW_ORIGIN_ADDR }}
+        SUPPORT_RATE_LIMIT_WINDOW_MINUTES: ${{ env.SUPPORT_RATE_LIMIT_WINDOW_MINUTES }}
+        SUPPORT_RATE_LIMIT_MAX_REQ: ${{ env.SUPPORT_RATE_LIMIT_MAX_REQ }}
+        SUPPORT_RATE_LIMIT_PATHS: ${{ env.SUPPORT_RATE_LIMIT_PATHS }}
+        NODE_ENV: ${{ env.NODE_ENV }}
       with:
         host: ${{ secrets.SUPPORT_SERVICE_HOST }}
         username: ${{ secrets.SUPPORT_SERVICE_USERNAME }}
@@ -58,6 +67,15 @@ jobs:
             echo "👹 Oops! Failed to reset branch"
             exit 1
           fi
+
+          # If env var path changes
+          # Update the EnvironmentFile in systemd service
+          if ! ./Services/ZenDesk/scripts/add-env-vars "$HOME"; then
+            echo "👹 Oops! Failed to add the environment variables for some reason..."
+            exit 1
+          fi
+          
+          echo "✅ The environment variables were processed successfully."
 
           commit_hash=$(git rev-parse HEAD)
           commit_msg=$(git log -1 --pretty=format:"%s")
