refactor: 💡 index html variable name

diff --git a/scripts/build/copy-video-content-src-to-dist b/scripts/build/copy-video-content-src-to-dist
--- a/scripts/build/copy-video-content-src-to-dist
+++ b/scripts/build/copy-video-content-src-to-dist
@@ -35,18 +35,23 @@ find "$src_content_dir" -type f -name "*.mp4" | while read -r src_file; do
   video_filename=$(basename "$src_file")
   dist_html_file="${src_file/src\/content/dist}"
   dist_html_dirname=$(dirname "$dist_html_file")
-  index_html="$dist_html_dirname/index.html"
+  index_html_file="$dist_html_dirname/index.html"
   target_replace_path="${dist_file/$dist_dir/}"
 
-  if ! grep -q "\./$video_filename" "$index_html"; then
+  if [[ ! -f "$index_html_file" ]]; then
+    echo "👹 Oops! Couldn't locate an index file in $index_html_file. The author is possibly not following the contributing conventions?"
+    exit 1
+  fi
+
+  if ! grep -q "\./$video_filename" "$index_html_file"; then
     continue
   fi
   
-  if ! sed_replace "s|\./$video_filename|$target_replace_path|g" "$index_html"; then
-    echo "❌ Failed to replace path in file $index_html"
+  if ! sed_replace "s|\./$video_filename|$target_replace_path|g" "$index_html_file"; then
+    echo "❌ Failed to replace path in file $index_html_file"
     exit 1
   else
-    echo "✅ Replaced path in $index_html from $video_filename to $target_replace_path"
+    echo "✅ Replaced path in $index_html_file from $video_filename to $target_replace_path"
   fi
 done
 
